### ISSUE TITLE
I wanna repeat your algorithm for search policies but don't understand some moments in paper.

### ISSUE THREAD

**Issue by kryack** [kakaobrain/fast-autoaugment#10]
I create this algorithm for voice-antispoofing problem.

Answer please for next some questions because i did not understand this from your paper (Fast AutoAugment):
1) Do you choose for imagenet only 120 classes (120 * 1000 = 120 000 pictures) and from this you randomly choose 6000 samples? Do you train all algorithm only on 6000 pictures? And what is the ratio Dm:Da in StratifiedShuffleSplit (test_size parameter)?
2) Is this continuous training on each step of algorithm? Or each iterations just started from random initialize model? 90 epoch (in your paper for resnet on imagenet) - it is on each training Dm set?
3) From each fold you get best 10 policies (each contain 5 sub-policies). And after each iteration of algorithm you choose 50 policies? It is too much! How do you choose best policies of this 50? And how do you apply this many policies in train? Are you choose it in random?
4) And how do you choose best policies on the end of the training?

I hope I described it clearly.
With love, Makarov Rostislav.

**Comment by ildoonet** [comment]
1. Yes, search algorithm run only with 6k pictures. Below is the partial code snippet I used.
```
    elif dataset == 'reduced_imagenet':
        # randomly chosen indices
        idx120 = [904, 385, 759, 884, 784, 844, 132, 214, 990, 786, 979, 582, 104, 288, 697, 480, 66, 943, 308, 282, 118, 926, 882, 478, 133, 884, 570, 964, 825, 656, 661, 289, 385, 448, 705, 609, 955, 5, 703, 713, 695, 811, 958, 147, 6, 3, 59, 354, 315, 514, 741, 525, 685, 673, 657, 267, 575, 501, 30, 455, 905, 860, 355, 911, 24, 708, 346, 195, 660, 528, 330, 511, 439, 150, 988, 940, 236, 803, 741, 295, 111, 520, 856, 248, 203, 147, 625, 589, 708, 201, 712, 630, 630, 367, 273, 931, 960, 274, 112, 239, 463, 355, 955, 525, 404, 59, 981, 725, 90, 782, 604, 323, 418, 35, 95, 97, 193, 690, 869, 172]
        total_trainset = torchvision.datasets.ImageFolder(root=os.path.join(dataroot, 'imagenet/train'), transform=transform_train)
        testset = torchvision.datasets.ImageFolder(root=os.path.join(dataroot, 'imagenet/val'), transform=transform_test)

        # compatibility
        total_trainset.train_labels = [lb for _, lb in total_trainset.samples]

        sss = StratifiedShuffleSplit(n_splits=1, test_size=len(total_trainset) - 500000, random_state=0)  # 4000 trainset
        sss = sss.split(list(range(len(total_trainset))), total_trainset.train_labels)
        train_idx, valid_idx = next(sss)

        # filter out
        train_idx = list(filter(lambda x: total_trainset.train_labels[x] in idx120, train_idx))
        valid_idx = list(filter(lambda x: total_trainset.train_labels[x] in idx120, valid_idx))
        test_idx = list(filter(lambda x: testset.samples[x][1] in idx120, range(len(testset))))

        train_labels = [idx120.index(total_trainset.train_labels[idx]) for idx in train_idx]
        for idx in range(len(total_trainset.samples)):
            if total_trainset.samples[idx][1] not in idx120:
                continue
            total_trainset.samples[idx] = (total_trainset.samples[idx][0], idx120.index(total_trainset.samples[idx][1]))
        total_trainset = Subset(total_trainset, train_idx)
        total_trainset.train_labels = train_labels

        for idx in range(len(testset.samples)):
            if testset.samples[idx][1] not in idx120:
                continue
            testset.samples[idx] = (testset.samples[idx][0], idx120.index(testset.samples[idx][1]))
        testset = Subset(testset, test_idx)
        print('reduced_imagenet train=', len(total_trainset))
```

2. I didn't understand fully. Please elaborate more.

3. Yes, TTA(Test Time Augmentation) performance was used for evaluate each policies and we select top-k. In our ablation study, the number of policies you select(we used 10 for each run) was not that important. You can reduce it like 5. Also, I believe that finding many policies in a efficient manner is a key reason for our performance.

4. We just choose best top-k policies for each cv set(=5) and we combine them.
