### ISSUE TITLE
Hopes  for  your search  code , I  think it  will  be  very  useful  to this world

### ISSUE THREAD

**Issue by heartInsert** [kakaobrain/fast-autoaugment#11]

**Comment by monkeyDemon** [comment]
Hopes too! I think it will be very useful, and I really want to try if this algorithm work to my project.
Is the author currently open-source search code now? I skimmed through the code and not found.

**Comment by ildoonet** [comment]
It will be released within one or two week! I'm cleaning up some of codes now...

**Comment by ildoonet** [comment]
@monkeyDemon @heartInsert Released. I tested all training codes and released trained model checkpoints. But note that I didn't tried to rerun the search phase due to our gpu resources. 

Closing this issue but if you have any question, please let me know with new issue.
