### ISSUE TITLE
Which ResNet50 did you use?

### ISSUE THREAD

**Issue by moskomule** [kakaobrain/fast-autoaugment#12]
Hi, I want to run your code for ImageNet, but it seems the ResNet-50 implementation is missing. 

In ` fast-autoaugment/FastAutoAugment/networks/__init__.py `,

```
from pretrainedmodels import models
...
model = models.resnet50(num_classes=num_class, pretrained=None)
```

but `pretrainedmodels` is not uploaded yet. Is this ResNet50 from torchvision or your original implementation?

**Comment by alashkari** [comment]
Install pretrainedmodels with "pip install pretrainedmodels"

**Comment by moskomule** [comment]
Thanks. It uses torchvision’s ResNet50
