### ISSUE TITLE
This line is different in the paper. 

### ISSUE THREAD

**Issue by emrahyigit** [kakaobrain/fast-autoaugment#24]
https://github.com/kakaobrain/fast-autoaugment/blob/e79d0c78a0fbb5126cc1bbb2cbf4d001d6f680d6/FastAutoAugment/archive.py#L106

**Comment by ildoonet** [comment]
@emrahyigit Thanks, we fixed it.
Also autoaugment code(https://github.com/tensorflow/models/blob/master/research/autoaugment/policies.py#L22) seems to be the final one. It is also different from the paper's one.

Let me know if you have any problems.
