### ISSUE TITLE
the search hangs

### ISSUE THREAD

**Issue by knsong** [kakaobrain/fast-autoaugment#25]
Hi, thank you for the work first.
But when I started a searching experiment on a ray cluster just using command `python search.py -c confs/wresnet40x2_cifar10_b512.yaml --dataroot ... --redis ...` without modifying the code much, it would be hanging. Was there anything wrong?
![hang](https://user-images.githubusercontent.com/11374482/68773169-10697900-0666-11ea-90d5-0ea6c8ade0b0.jpg)

**Comment by KhrystynaFaryna** [comment]
> Hi, thank you for the work first.
> But when I started a searching experiment on a ray cluster just using command `python search.py -c confs/wresnet40x2_cifar10_b512.yaml --dataroot ... --redis ...` without modifying the code much, it would be hanging. Was there anything wrong?
> ![hang](https://user-images.githubusercontent.com/11374482/68773169-10697900-0666-11ea-90d5-0ea6c8ade0b0.jpg)

Hi, did you figure out what was the reason behind the hanging?
