### ISSUE TITLE
how to gather the trained models on different workers?

### ISSUE THREAD

**Issue by knsong** [kakaobrain/fast-autoaugment#26]
HI, @ildoonet thanks for the work first, but during running the code `python search.py -c confs/wresnet40x2_cifar10_b512.yaml --dataroot ... --redis ...` on a Ray cluster, I find the header worker can't gather the models trained on worker nodes for the subsequent searching policy stage e.g. the main process on header node will throw  exception: `No such file or directory: '/FastAutoAugment/models/cifar10_wresnet40_2_ratio0.4_fold0.model`. So can you tell me how did you train end-to-end using  `python search.py -c confs/wresnet40x2_cifar10_b512.yaml --dataroot ... --redis ...` on the Ray cluster which has multiple nodes working in parallel?

**Comment by ildoonet** [comment]
@knsong We used network storage for this. Without explicit gathering process, model files will be saved in the same directory in NAS. 

But since this is very special specification, I will consider implement explciti gathering process. 

Thanks.

**Comment by knsong** [comment]
> @knsong We used network storage for this. Without explicit gathering process, model files will be saved in the same directory in NAS.
> 
> But since this is very special specification, I will consider implement explciti gathering process.
> 
> Thanks.

Thank you for the reply. And I finally also used NAS to sync files.
