### ISSUE TITLE
GPUs for searching

### ISSUE THREAD

**Issue by yichuan9527** [kakaobrain/fast-autoaugment#28]
Hello, I see in the serarching code setting `num-search` 200 and `resources_per_trial` 1. Does this denote that fast autoaugment needs 200 gpus for searching?

**Comment by ildoonet** [comment]
@yichuan9527 No, num-search means trial numbers(sampling numbers) for augmentation policies. But if you use more gpus, this trial phase would be done faster.

**Comment by yichuan9527** [comment]
I get it. Thanks very much.
