### ISSUE TITLE
Training on multiple GPUs

### ISSUE THREAD

**Issue by miriam124578** [kakaobrain/fast-autoaugment#30]
I'd like to train with this config: https://github.com/kakaobrain/fast-autoaugment/blob/master/confs/pyramid272_cifar10_b64.yaml

with multiple GPUs (as training on one takes about 600 hours). Is there any parameters adjustment to that config that you recommend to make?

**Comment by ildoonet** [comment]
@miriam124578 I trained the pyramidnet with 2 or 4 V100 gpus without changing current configurations.

If you want to leverage more gpus(eg. multiple gpu nodes), I believe that you can increase batch-size and learning-rate linearly. For example, if you increase batch-size from 64 to 128(2x), then you should double learning-rate. 

If batch-size is large(more then 256), you might want to use 'warm-up' scheduling. See other configurations like : https://github.com/kakaobrain/fast-autoaugment/blob/master/confs/wresnet28x10_cifar10_b512.yaml#L11
