### ISSUE TITLE
cutout on ImageNet

### ISSUE THREAD

**Issue by snownus** [kakaobrain/fast-autoaugment#33]
@ildoonet From config files, it seems there is no cutout on search stage on reduced_imagenet and eval stage on ImageNet. Would you like to confirm/share the detailed information about cutout on ImageNet?

**Comment by ildoonet** [comment]
@snownus We don't use cutout for ImageNet. We use it only for CIFAR-10/100 and SVHN. It is same as Google's AutoAugment.

**Comment by snownus** [comment]
@ildoonet thanks so much for your instant reply.
