### ISSUE TITLE
A  question about  search.py 

### ISSUE THREAD

**Issue by heartInsert** [kakaobrain/fast-autoaugment#35]
Hi ,  man  I  want to  excute  seach.py  in  cifar 10  ,   I  notice  that  ` fa_reduced_cifar10` is   the  result  you  got  ,  but    in   `wresnet40x2_cifar10_b512.yaml`,  there  alreayd  exist  a  key  `aug: fa_reduced_cifar10`  ,      should I  delete  it   and   type  with  nothing ?

**Comment by ildoonet** [comment]
@heartInsert You are right. You need to add "--aug default" parameter when you run search.py file.

**Comment by heartInsert** [comment]
Ok, I  get  it ,thanks for your help .
