### ISSUE TITLE
Would you like to provide the training confs of CIFAR-100?

### ISSUE THREAD

**Issue by latstars** [kakaobrain/fast-autoaugment#38]
Thanks for the publication of codes.
In order to evaluate the performance of CIFAR-100, we need the hyper-parameters for the training of CIFAR-100. Would you like to provide the training confs of CIFAR-100?

**Comment by ildoonet** [comment]
@latstars 

We use same hyperparameters as cifar-10.

Change dataset argument to 'cifar100' from 'cifar10'. 

e.g

python train.py -c conf/...yaml --dataset cifar100
