### ISSUE TITLE
Questions about the initialization of the Ray server.

### ISSUE THREAD

**Issue by XuChunqiao** [kakaobrain/fast-autoaugment#53]
Hi, I've tried to run the code for searching policies, but I have trouble in initializing the Ray server. 
It seems that there is someting wrong with the code  _"ray.init(redis_address=args.redis)"_ in search.py Line 164

Traceback (most recent call last):
  File "search.py", line 166, in <module>
    ray.init(redis_address=args.redis)
  File "/home/xcq/anaconda3/envs/pytorch-video/lib/python3.6/site-packages/ray/worker.py", line 1425, in init
    redis_address = services.address_to_ip(redis_address)
  File "/home/xcq/anaconda3/envs/pytorch-video/lib/python3.6/site-packages/ray/services.py", line 145, in address_to_ip
    ip_address = socket.gethostbyname(address_parts[0])
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)

Any suggestion about what I could be doing wrong/ how to workaround this?
ray version==0.6.5

**Comment by koi-boy** [comment]
请问解决了没有？

**Comment by XuChunqiao** [comment]
> 请问解决了没有？

**Comment by XuChunqiao** [comment]
> > 请问解决了没有？

解决了。
我把ray.init(redis_address=args.redis) 换成ray.init(num_cpus=8, num_gpus=2)就可以了

**Comment by koi-boy** [comment]
> > > 请问解决了没有？
> 
> 解决了。
> 我把ray.init（redis_address = args.redis）换成ray.init（num_cpus = 8，num_gpus = 2）就可以了

谢谢谢谢，我去尝试下

**Comment by MaDaJie2706** [comment]
你好，请问运行这个代码必须要搭建ray集群么

**Comment by MaDaJie2706** [comment]
@XuChunqiao 
我将search.py 中@ray.remote(num_gpus=4, max_calls=1) 和ray.init(redis_address=args.redis) 改为@ray.remote(num_gpus=1, max_calls=1) 和ray.init() ，运行了两个多小时都没进展，一直卡在那了
![VB2YUAEDVD5R9{HR4@65SRS](https://user-images.githubusercontent.com/60532942/131445887-99b2a354-7f92-4de2-9406-8fb57c42c8ac.png)
