### ISSUE TITLE
ValueError in search.py

### ISSUE THREAD

**Issue by Hhhhhhao** [kakaobrain/fast-autoaugment#58]
When I run search.py, I got an error by register_trainable

`ValueError: Unknown argument found in the Trainable function. The function args must include a 'config' positional parameter. Any other args must be 'checkpoint_dir'. Found: ['augs', 'rpt']`

Any ideas how to fix this?

**Comment by zherlock030** [comment]
Try to use lower version of ray, such as 0.8.1
