### ISSUE TITLE
requirement 'ascii' codec can't decode byte 0xec

### ISSUE THREAD

**Issue by zihaozhang9** [kakaobrain/fast-autoaugment#7]
Hello!
I use python3.6.5
I install use  `pip install git+https://github.com/wbaek/theconf.git`
I get:
Collecting git+https://github.com/wbaek/theconf.git
Cloning https://github.com/wbaek/theconf.git to /tmp/pip-req-build-pun46x94
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in 
File "/tmp/pip-req-build-pun46x94/setup.py", line 19, in 
long_description = fp.read()
File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 449: ordinal not in range(128)

**Comment by ildoonet** [comment]
@zihaozhang9 
https://github.com/wbaek/theconf/pull/11

One of my great colleagues just fixed this issue. Please try again.

**Comment by zihaozhang9** [comment]
> @ zihaozhang9 
> [wbaek / theconf＃11](https://github.com/wbaek/theconf/pull/11)
> 
> 我的一位同事刚刚解决了这个问题。请再试一次。

OK!very thinkes~I have successfully installed

**Comment by sublee** [comment]
Thanks for confirming. I close this issue.
